// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef test2_h
#define test2_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class SimpleUI {
public:
  SimpleUI();
};
#endif
