// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "test2.h"

SimpleUI::SimpleUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(560, 330);
    w = o;
    o->user_data((void*)(this));
    { new Fl_Button(25, 25, 225, 55, "test");
    } // Fl_Button* o
    { new Fl_Button(25, 100, 225, 55, "test2");
    } // Fl_Button* o
    { new Fl_Button(275, 20, 260, 135, "test3");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show();
}



#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

int main(int argc, char **argv) 
{
 
  SimpleUI();
  return Fl::run();
}



